modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "oc2_example_block_entity"
version = "1.0.0"
displayName = "OC2 Example: Block Entity"

[[dependencies.oc2_example_block_entity]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"

[[dependencies.oc2_example_block_entity]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"

[[dependencies.oc2_example_block_entity]]
modId = "oc2"
type = "optional"
versionRange = "[0,)"
