[versions]
minecraft = "1.21.1"
parchment-minecraft = "1.21.1"
parchment-mappings = "2024.11.17"

architectury = "13.0.11"
injectables = "1.0.10"
manual = "1.2.7"

ceres = "0.0.7"
sedna = "4.0.1"
sedna-buildroot = "0.2.2"
sedna-cpm = "0.1.0"
vox2mc = "1.0.0"

fabric-loader = "0.19.3"
fabric-api = "0.116.15+1.21.1"

jei = "19.43.0.395"

fabric-energy = "4.1.0"
fabric-forgeConfigPort = "21.1.6"

neoforge-platform = "21.1.248"
neoforge-loader = "4"

[plugins]
loom = { id = "dev.architectury.loom", version = "1.17-SNAPSHOT" }
architectury = { id = "architectury-plugin", version = "3.5-SNAPSHOT" }
shadow = { id = "com.gradleup.shadow", version = "9.4.3" }
spotless = { id = "com.diffplug.spotless", version = "6.22.0" }

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
architectury-api = { group = "dev.architectury", name = "architectury", version.ref = "architectury" }
architectury-injectables = { group = "dev.architectury", name = "architectury-injectables", version.ref = "injectables" }

ceres = { group = "li.cil.ceres", name = "ceres", version.ref = "ceres" }
sedna = { group = "li.cil.sedna", name = "sedna", version.ref = "sedna" }
sedna-buildroot = { group = "li.cil.sedna", name = "sedna-buildroot", version.ref = "sedna-buildroot" }
sedna-cpm = { group = "li.cil.sedna", name = "sedna-cpm", version.ref = "sedna-cpm" }
vox2mc = { group = "li.cil.vox2mc", name = "vox2mc", version.ref = "vox2mc" }

fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-architectury = { group = "dev.architectury", name = "architectury-fabric", version.ref = "architectury" }

common-manual-api = { group = "li.cil.markdown_manual", name = "markdown_manual-1.21.1-api", version.ref = "manual" }
fabric-manual = { group = "li.cil.markdown_manual", name = "markdown_manual-1.21.1-fabric", version.ref = "manual" }

jei-common-api = { group = "mezz.jei", name = "jei-1.21.1-common-api", version.ref = "jei" }
jei-neoforge = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version.ref = "jei" }
jei-fabric = { group = "mezz.jei", name = "jei-1.21.1-fabric", version.ref = "jei" }

fabric-energy = { group = "teamreborn", name = "energy", version.ref = "fabric-energy" }
fabric-forgeConfigPort = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-fabric", version.ref = "fabric-forgeConfigPort" }

neoforge-platform = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge-platform" }
neoforge-architectury = { group = "dev.architectury", name = "architectury-neoforge", version.ref = "architectury" }

neoforge-manual = { group = "li.cil.markdown_manual", name = "markdown_manual-1.21.1-neoforge", version.ref = "manual" }
