modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "oc2gametest"
version = "0.0.0"
displayName = "OpenComputers II Game Tests"
description = '''
Game test suite. Run with ./gradlew :neoforge:runGameTestServer
'''

[[dependencies.oc2gametest]]
modId = "architectury"
type = "required"
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.oc2gametest]]
modId = "oc2"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
