#!/bin/sh

TERMINFO_PROFILE="/etc/profile.d/terminfo.sh"

# Registers terminfo environment variables in global profile config if they don't exist yet
start() {
    if [ ! -f $TERMINFO_PROFILE ]; then
        echo "TERMINFO=/usr/lib/terminfo/v/vt100" >$TERMINFO_PROFILE
        echo "COLUMNS=80" >>$TERMINFO_PROFILE
        echo "LINES=24" >>$TERMINFO_PROFILE
    fi
    return 0
}

stop() {
    return 0
}

reload() {
    return 0
}

case "$1" in
start | stop | reload)
    "$1"
    ;;
restart)
    reload
    ;;
*)
    echo "Usage: $0 {start|stop|reload|restart}"
    exit 1
    ;;
esac

exit $?
